import Decimal from "decimal.js";
import {insert} from "../repositories/product.repository.js";
import {productResponse} from "../utils/product.mapper.js";
import {uuid} from "../utils/reference.js";
import {jsonText} from "../utils/json.js";
const blank=v=>v===undefined||v===null||String(v).trim()==='';
const text=v=>v===null||String(v??'').trim().toLowerCase()==='null'?null:(blank(v)?'':String(v).trim());
const num=v=>{if(blank(v)||String(v).trim().toLowerCase()==='null')return null;const n=Number(v);return Number.isFinite(n)?n:null;};
const money=v=>v===null?null:new Decimal(v).toFixed(2);
const json=v=>v===null?null:(v===undefined||blank(v)?jsonText([],[]):typeof v==='string'?v:jsonText(v,[]));
function normalize(p,now){const price=num(p.price);let dp=blank(p.discountPercent)?0:Number(p.discountPercent);if(!Number.isFinite(dp))dp=0;let da=num(p.discountAmount),amount=num(p.amount);if(price!==null){da=new Decimal(price).mul(dp).div(100).toDecimalPlaces(2,Decimal.ROUND_HALF_UP);amount=new Decimal(price).minus(da);}return{id:String(p.rowid??'').trim()||uuid(),sku:text(p.sku),category:text(p.category),name:text(p.name),contents:text(p.contents),price:money(price),discountPercent:dp,discountAmount:money(da),amount:money(amount),currency:text(p.currency),taxRate:num(p.taxRate),image:text(p.image),tags:p.tags===null?null:json(p.tags),stockQuantity:num(p.stockQuantity),minOrderQty:num(p.minOrderQty),maxOrderQty:num(p.maxOrderQty),status:text(p.status)||'in_stock',backorderAllowed:p.backorderAllowed??false,active:p.active??true,crmProductId:text(p.crmProductId),lastUpdated:p.lastUpdated??now,source:text(p.source),descriptionVideo:text(p.descriptionVideo),updatedAt:p.updatedAt??now,uiFlags:p.uiFlags===null?null:(p.uiFlags===undefined||blank(p.uiFlags)?jsonText({},{}):typeof p.uiFlags==='string'?p.uiFlags:jsonText(p.uiFlags,{}))};}
export async function replaceAllProducts(db,products){const client=await db.connect();try{await client.query('BEGIN');const normalized=products.map(p=>normalize(p,new Date()));const ids=new Set();for(const p of normalized){if(ids.has(p.id))throw new Error(`Duplicate rowid "${p.id}" in Excel file.`);ids.add(p.id);}await client.query('DELETE FROM products');const rows=[];for(const p of normalized)rows.push(await insert(client,p));await client.query('COMMIT');return rows.map(productResponse);}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
